### ISSUE TITLE
Does it work for you?

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/stalkerhek#4]
Simple question - **does it work for you?**

I wrote this application so I can see IPTV on PS3 and VLC, and it did work for me at some extent. I tried to make it as perfect as I could, but I only had a single box to test it. I have no clue if it works for anyone else.

Let me know in the comments if this app does work for you. I did not expect any stars or forks for this project, but seems there is a demand for this app :D

**Comment by kettenbach-it** [comment]
Hi,

I'm glad you asked!
In principle, I think it's a very good idea and that we should continue to work on it.
Accordingly, I started working on the project in November.
I use a MAG256 and for many portals you now need this beefier version with more memory because the MAG254 is too small.
I have analysed and documented the protocol of the MAG256. This is a terrible job and I am still not 100% sure if what I found out is true.
The whole thing was running in principle before Christmas, but was still quite unfinished.
Unfortunately, I have been quite distracted from it in the meantime, as I have to take care of some trouble spots because of the Covid pandemic.
I had intended to write and upload a pull request for MAG256 set-top box support and for a little more robustness (that's the hard part).
I just started the program - but it didn't run - there was only an empty channel list. I have to check my STB to see if my account is still OK. Sometimes the operator forgets to renew it...

Greetings
Volker

**Comment by Dogenymous** [comment]
Hii man, 

This is an awesome script that have a lot of potential. 

I have tested with 2 different portals, and had some different issues on both of them. 

You got the config of the one where the stream was stopping after like 30 / 40 seconds of playtime, and when i tested with another portal, i had the same issue as mentioned here https://github.com/erkexzcx/stalkerhek/issues/1#issuecomment-753492906 . 

The channel list shows, but the player keeps skipping them. I can share this config with you too, if you are interested.

Thanks again. 

Regards / Doge

**Comment by erkexzcx** [comment]
The issue where stream was stopping every 30 seconds was fixed with latest commits. I've explained why it was happening here: https://github.com/erkexzcx/stalkerhek/issues/3#issuecomment-803622163 so please try again and see if it no longer happens.

> but the player keeps skipping them.

Yes, send me to erikmnkl@gmail.com so I can debug why it is happening. :)

**Comment by erkexzcx** [comment]
With latest commits I think I've fixed 2 separate issues that caused stream to stop after short period of time (few to ~30 seconds). Please check against latest code in this repo and if it still doesn't work - open a new issue.
